language: csharp
solution: LazyLibrary.sln
install:
  - nuget restore LazyLibrary.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - bash . ./BuildScripts/tag.sh
  - xbuild /p:Configuration=Release LazyLibrary.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./LazyLibraryTests/bin/Release/LazyLibrary.Tests.dll
