nuget:
  account_feed: true

before_build:
  - nuget restore

configuration: Release

build:
  project: LazyStorage.sln
  verbosity: minimal

after_build:
  - cmd: nuget pack LazyStorage\LazyStorage.csproj -version "%GitVersion_NuGetVersion%" -prop "target=Release"
  - cmd: appveyor PushArtifact "LazyStorage.%GitVersion_NuGetVersion%.nupkg"

deploy:
  - provider: GitHub
    auth_token:
      secure: A7+/5adwhz9NXkJeVJpckt7wIcfIOVr1M8KPMHrOD+TknNaV6CX2XrKR21+QS9ko
    artifact: /.*\.nupkg/
    draft: false
    prerelease: false
    description: ''
    on:
      appveyor_repo_tag: true
  - provider: NuGet
    api_key:
      secure: mJ21/ayGYSXI/29RaN75qvcuoYDIq8RKmq7PkBlkQ8WWUnfZ063XDmhNrELUKwXP
    skip_symbols: false
    on:
      appveyor_repo_tag: true