nuget:
  account_feed: true

before_build:
  - nuget restore

configuration: Release

build:
  project: LazyStorage.sln
  verbosity: minimal

after_build:
  - cmd: nuget pack LazyStorage\LazyStorage.csproj -version "%GitVersion_NuGetVersion%" -prop "target=Release"
  - cmd: appveyor PushArtifact "LazyStorage.%GitVersion_NuGetVersion%.nupkg"