before_build:
  - dotnet restore
  - choco install GitVersion.Portable
  - GitVersion /output buildserver

configuration: Release
image: Visual Studio 2017 Preview

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '%GitVersion_AssemblySemVer%'
  package_version: '%GitVersion_FullSemVer%'

build:
  project: LazyStorage.sln
  verbosity: minimal

after_build:
  - cmd: dotnet pack LazyStorage\LazyStorage.csproj -c Release /p:PackageVersion=%GitVersion_NuGetVersion%"
  - cmd: appveyor PushArtifact "LazyStorage\bin\release\LazyStorage.%GitVersion_NuGetVersion%.nupkg"

deploy:
  - provider: GitHub
    auth_token:
      secure: A7+/5adwhz9NXkJeVJpckt7wIcfIOVr1M8KPMHrOD+TknNaV6CX2XrKR21+QS9ko
    artifact: /.*\.nupkg/
    draft: false
    prerelease: false
    description: ''
    on:
      appveyor_repo_tag: true
  - provider: NuGet
    api_key:
      secure: mJ21/ayGYSXI/29RaN75qvcuoYDIq8RKmq7PkBlkQ8WWUnfZ063XDmhNrELUKwXP
    skip_symbols: false
    on:
      appveyor_repo_tag: true
